name: deploys
on: 
  push:
    branches:
      - deploy

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js lts/*
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.DEPLOY_GCP_SERVICE_ACCOUNT_JSON }}'

    - name: Install dependencies
      run: npm ci

    - name: Build docs
      run: npm run docs:build
      env:
        NODE_ENV: production
        
    - name: Add version file
      run: npm pkg get --json version name > docs/.vuepress/dist/_version.json

    - name: Deploy
      run: npx firebase deploy --only hosting